table 'New Measures'
	lineageTag: 412f03aa-a38c-42bd-835c-1e1680b99842

	measure 'Total Cost' = SUMX('US_Regional_Sales_Data','US_Regional_Sales_Data'[Order Quantity] * 'US_Regional_Sales_Data'[Unit Cost])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1ce12bfa-e05c-4ef0-a803-e74df3774d2e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Sales' = SUMX(US_Regional_Sales_Data, US_Regional_Sales_Data[Unit Price] * US_Regional_Sales_Data[Order Quantity])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8cb537c1-eb8d-4942-baeb-2c82b97a1e20

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Quantity Sold' = SUM('US_Regional_Sales_Data'[Order Quantity])
		lineageTag: c35ac7d2-62b2-4897-af49-6cd506b8cc3e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit' = [Total Sales] - [Total Cost]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2d866f59-3dd1-4dfd-87ad-6b2945d9bdf2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Average Discount' = AVERAGE('US_Regional_Sales_Data'[Discount Applied])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6c7f3df6-1724-458e-baa8-17b28df6ec11

	measure 'Avg Unit Cost' = AVERAGE('US_Regional_Sales_Data'[Unit Cost])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3b12b4e3-8f81-4be0-92a1-f10cd97ae166

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Gross Margin %' = DIVIDE([Gross Profit], [Total Sales])
		lineageTag: da74c02c-b099-45ae-a944-a35acef25df9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unit Profit' = DIVIDE([Gross Profit], [Total Quantity Sold])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 78c64d4b-170c-4ce7-9139-663471021466

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Avg Unit Price' = AVERAGE('US_Regional_Sales_Data'[Unit Price])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 60c24146-e444-4404-8d40-488c32fa8faa

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition 'New Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measures = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Measures", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Measures", "Total"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"Total"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

