table US_Regional_Sales_Data
	lineageTag: 774ab6bc-ec76-48fd-9f50-a0777417be72

	column OrderNumber
		dataType: string
		lineageTag: ef728bdc-bd7a-45e1-ae0b-cd58fd4f282c
		summarizeBy: none
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column 'Sales Channel'
		dataType: string
		lineageTag: aced9dde-03e0-4a50-93b4-a7823debc2f6
		summarizeBy: none
		sourceColumn: Sales Channel

		annotation SummarizationSetBy = Automatic

	column WarehouseCode
		dataType: string
		lineageTag: fd1f43a0-8b6e-4f14-aad8-4b2b26f55d42
		summarizeBy: none
		sourceColumn: WarehouseCode

		annotation SummarizationSetBy = Automatic

	column ProcuredDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1d0ad6ad-d5c1-43ed-8baf-00eeb85d7be6
		summarizeBy: none
		sourceColumn: ProcuredDate

		variation Variation
			isDefault
			relationship: 28223986-9cd2-41f3-a903-64242851e516
			defaultHierarchy: LocalDateTable_caa1dea8-e8d3-49d1-a395-873326ac9a9e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 869a4335-4960-4bba-b90b-b406ef388ac7
		summarizeBy: none
		sourceColumn: OrderDate

		variation Variation
			isDefault
			relationship: 856022be-fed4-4387-807b-2f5f52a94731
			defaultHierarchy: LocalDateTable_e2806cda-0a4a-40a4-ae6d-77b70700493a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ShipDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 13fc7dad-2129-4633-b601-2dd6311f822d
		summarizeBy: none
		sourceColumn: ShipDate

		variation Variation
			isDefault
			relationship: a44a5c60-96a4-4fb8-ada3-c7f7740c3de6
			defaultHierarchy: LocalDateTable_4087b86f-5039-44a3-bd86-5d2c3d4d83f6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DeliveryDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 97ad9139-514f-4453-8a44-b95ef73c6fb0
		summarizeBy: none
		sourceColumn: DeliveryDate

		variation Variation
			isDefault
			relationship: 23d87cc6-a15a-4844-b96a-135acb46c02c
			defaultHierarchy: LocalDateTable_b230c852-ad38-485b-82ac-e3e0bc6ffe57.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CurrencyCode
		dataType: string
		lineageTag: 9e336b59-ce99-4325-ace8-4f5918a6e968
		summarizeBy: none
		sourceColumn: CurrencyCode

		annotation SummarizationSetBy = Automatic

	column _SalesTeamID
		dataType: int64
		formatString: 0
		lineageTag: 1794369d-eab0-409a-a690-bc9232e0e765
		summarizeBy: count
		sourceColumn: _SalesTeamID

		annotation SummarizationSetBy = Automatic

	column _CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 786cad5a-3f9e-41af-be6e-ebb51f3bb2df
		summarizeBy: count
		sourceColumn: _CustomerID

		annotation SummarizationSetBy = Automatic

	column _StoreID
		dataType: int64
		formatString: 0
		lineageTag: 3f3cbce8-afc4-400b-a67f-1aeb24f72ede
		summarizeBy: count
		sourceColumn: _StoreID

		annotation SummarizationSetBy = Automatic

	column _ProductID
		dataType: int64
		formatString: 0
		lineageTag: c4c412ff-01f1-4538-a198-02080c491530
		summarizeBy: count
		sourceColumn: _ProductID

		annotation SummarizationSetBy = Automatic

	column 'Order Quantity'
		dataType: int64
		formatString: 0
		lineageTag: 4b30861a-804e-494a-9d17-9316de30832a
		summarizeBy: sum
		sourceColumn: Order Quantity

		annotation SummarizationSetBy = Automatic

	column 'Discount Applied'
		dataType: double
		lineageTag: e96b3d0c-cd1e-499e-a2ca-b3b935950b16
		summarizeBy: sum
		sourceColumn: Discount Applied

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Cost'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 16872877-ad6d-4203-9fe0-95b8d72c9c37
		summarizeBy: sum
		sourceColumn: Unit Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Unit Price'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 6bd957e8-8a5e-4880-9ef8-00916cb8bbaf
		summarizeBy: sum
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition US_Regional_Sales_Data = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\prath\OneDrive\Desktop\PGDM\Trimester 3\BA\assignment\Dashboard\US_Regional_Sales_Data.csv"),[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Added Custom" = Table.AddColumn(#"Promoted Headers", "NewOrderDate", each let
				  parts = Text.Split([OrderDate], "/"),
				  day = parts{0},
				  month = parts{1},
				  year = parts{2},
				  fullYear = if Text.Length(year) = 2 then "20" & year else year
				in
				  Date.FromText(day & "/" & month & "/" & fullYear)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"NewOrderDate", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"NewOrderDate"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns","/18","/2018",Replacer.ReplaceText,{"OrderDate"}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Replaced Value", {{"OrderDate", type date}}, "en-GB"),
				    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type with Locale","/18","/2018",Replacer.ReplaceText,{"ShipDate"}),
				    #"Changed Type with Locale1" = Table.TransformColumnTypes(#"Replaced Value1", {{"ShipDate", type date}}, "en-GB"),
				    #"Replaced Value2" = Table.ReplaceValue(#"Changed Type with Locale1","/18","/2018",Replacer.ReplaceText,{"DeliveryDate"}),
				    #"Changed Type with Locale2" = Table.TransformColumnTypes(#"Replaced Value2", {{"DeliveryDate", type date}}, "en-GB"),
				    #"Replaced Value3" = Table.ReplaceValue(#"Changed Type with Locale2","/18","/2018",Replacer.ReplaceText,{"ProcuredDate"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","/17","/2017",Replacer.ReplaceText,{"ProcuredDate"}),
				    #"Changed Type with Locale3" = Table.TransformColumnTypes(#"Replaced Value4", {{"ProcuredDate", type date}}, "en-GB"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type with Locale3",{{"Unit Cost", Currency.Type}, {"Unit Price", Currency.Type}, {"Discount Applied", type number}, {"Order Quantity", Int64.Type}, {"_ProductID", Int64.Type}, {"_StoreID", Int64.Type}, {"_CustomerID", Int64.Type}, {"_SalesTeamID", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

